# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c516e6bcc99a95a2151af047d992446a56b11c03a18d7c60202034302496ee899025d205906feba50d13310658062bf7fd4bcf26778a7bc5a7adbd71d9cd8e7

test:
  secret_key_base: b824d646e671406e2002c32003b6f840bd51249296d54a25d191a7ae9fd51499709addc2b1c8c5b0a69d23b28218b572b65fc9c126721ca0272551a308c7bfeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
